# Generated by Django 4.0.3 on 2022-04-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_allergy_drink_set'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
